### ISSUE TITLE
Support parsing DFPT results from the castep file

### ISSUE THREAD

**Issue by amundmr** [aplowman/castep-parse#2]
https://github.com/aplowman/castep-parse/blob/678e9770c3e84f6e6f6d0e87c394124b39c6cbc4/castep_parse/readers.py#L862

It seems that if the version finding fails, the whole reader fails. This is because unless the version is found, no "version" variable is made, so the next if statement fails.

Can this be avoided by using an else statement and setting the version to nan?

> Traceback (most recent call last):
>   File ".\importer.py", line 95, in <module>        
>     data = cp.readers.read_castep_file(fn1)
>   File "c:\users\amund\documents\megasync\prosjekter\castep-parse\castep_parse\utils.py", line 391, in decorated
>     return func(lines, *args, **kwargs)
>   File "c:\users\amund\documents\megasync\prosjekter\castep-parse\castep_parse\readers.py", line 64, in read_castep_file
>     run = parse_castep_run(run_str, run_idx)
>   File "c:\users\amund\documents\megasync\prosjekter\castep-parse\castep_parse\readers.py", line 703, in parse_castep_run
>     header = parse_castep_file_header(header_str)
>   File "c:\users\amund\documents\megasync\prosjekter\castep-parse\castep_parse\readers.py", line 866, in parse_castep_file_header        
>     if not version:
> UnboundLocalError: local variable 'version' referenced before assignment

**Comment by aplowman** [comment]
@amundmr, the idea behind "runs" is that multiple runs of Castep may output to the same `.castep` file, for instance when continuing a simulation from a checkpoint. I can see how to fix the version/header issue. However, what information would you like to be parsed from the file? Currently, none of the results from the DFPT will be parsed, because I only used `castep-parse` for single point and geometry optimisation simulations.

**Comment by amundmr** [comment]
Alright. Sorry, I think it has become obvious that I am not all that familiar with .castep files. I have actually not generated these files myself. The data I am looking to read is as follows:

- species
- unit cell
- lattice parameters
- coordinates of elements
- point group
- which modes are raman active (and at which frequencies)
- which modes are IR active (and at which frequencies)
- Optical and DC permittivity
- optical and static polarisability
- born effective charge for all elements

To be honest I am not sure if any of these are specific to the DFPT simulation.
